### ISSUE TITLE
FireSass has been replaced by FireCompass

### ISSUE THREAD

**Issue by Nafes** [richthegeek/phpsass#169]
Thank you for the great library and Drupal modules. Here are some patches for adding support of FireCompass: https://www.drupal.org/node/2312869.

**Comment by joejoseph00** [comment]
Here is the patch if interested https://www.drupal.org/files/issues/sassy-phpsass-2312869-1-D7-do-not-test.patch
I just applied it to my cloned copy of this library and it's applied without warnings.

**Comment by joejoseph00** [comment]
see pull request details here: 
https://github.com/richthegeek/phpsass/pull/178

**Comment by joejoseph00** [comment]
Nafes, do you have enough information to fix this?  if you can fix this just make another pull request and run it against ci again.  should be fairly easy
