### ISSUE TITLE
@charset is parsed incorrectly

### ISSUE THREAD

**Issue by dmromanov** [richthegeek/phpsass#177]
```@charset "utf-8";```
resulits in 
```@charset "utf-8" {
   }```

This should be translated without changes.

**Comment by joejoseph00** [comment]
The regex here should stop on \n (line return) I think.

When compiling scss the charset takes up the next css class, should just output @charset "utf8";
instead i'm seeing this:
@charset "UTF-8"html {
font-size: 16px; }

expecting:
@charset "UTF-8";
html { font-size: 16px; }

I'll try to fix the regex.
